# Generated by Django 4.1.2 on 2022-10-07 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Категорія"
                    ),
                ),
                ("slug", models.SlugField(allow_unicode=True, max_length=100)),
                (
                    "parent_cat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                        verbose_name="Батьківська категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Продавець")),
                ("slug", models.SlugField(allow_unicode=True, max_length=100)),
                (
                    "logo_url",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Лого"
                    ),
                ),
                ("site", models.URLField(blank=True, null=True, verbose_name="Сайт")),
            ],
            options={
                "verbose_name": "Merchant",
                "verbose_name_plural": "Merchants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        default="Невідомо",
                        max_length=64,
                        unique=True,
                        verbose_name="Виробник",
                    ),
                ),
                ("slug", models.SlugField(allow_unicode=True, max_length=100)),
                (
                    "logo_url",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Лого"
                    ),
                ),
                ("site", models.URLField(blank=True, null=True, verbose_name="Сайт")),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prod_id",
                    models.CharField(
                        max_length=12, verbose_name="Ідентифікатор продавця"
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Код продавця")),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=512, verbose_name="Найменування"
                    ),
                ),
                ("slug", models.SlugField(allow_unicode=True, max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Опис"
                    ),
                ),
                (
                    "picture",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Картинка"
                    ),
                ),
                (
                    "guarantee",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Гарантія"
                    ),
                ),
                (
                    "stock",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Наявність"
                    ),
                ),
                (
                    "oldprice",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Стара ціна",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Ціна",
                    ),
                ),
                ("redirect_url", models.URLField(verbose_name="Посилання на товар")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                        verbose_name="Категорія",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.merchant",
                        verbose_name="Продавець",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.vendor",
                        verbose_name="Виробник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-id"],
            },
        ),
    ]
